name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows, ubuntu]

    runs-on: ${{ matrix.os }}-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish --nologo -a x64 -c Release -o publish -p:PublishReadyToRun=true
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: binary-${{ matrix.os }}
        path: publish
